name: Run Flutter Tests

on:
  pull_request:
    branches:
      - main  # Define que o workflow roda em PRs direcionados para a branch "main"

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest  # Usa um ambiente Linux para rodar os testes

    steps:
      - name: Checkout código
        uses: actions/checkout@v4  # Baixa o código do repositório

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.16.2  # Ajuste para a versão que você está usando
          cache: true  # Cache para melhorar a velocidade dos builds

      - name: Instalar dependências
        run: flutter pub get

      - name: Gerar arquivos gerados automaticamente (mocks e retrofit)
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Rodar testes
        run: flutter test
